### ISSUE TITLE
Kint for Laravel with Twig templates

### ISSUE THREAD

**Issue by altrugon** [kint-php/kint#100]
Would it be possible to extend the Laravel version of Kint to make it work with twig templates?

Thanks.

**Comment by raveren** [comment]
I haven't used Laravel yet, what do you mean exactly? Formatting, internal variable omission or what?

**Comment by altrugon** [comment]
I tried the Kint extension for Laravel and it worked fine on the PHP files (Controllers, Models, etc), and I guess that it would also work fine on the Laravel views (Blade templates) but on the project I'm working on we are not using the Blade template system but Twig templates. I know Twig has the debug() function but the output is not as pretty as the Kint's output.

I'm aware Kint is a debugging helper for PHP but according to description of <a href="https://github.com/barelon/CgKintBundle">CgKintBundle</a> Kint can be use on the Twig templates too.

My particular problem is that we are using Twig on Laravel and not Symphony, that's why I was wondering if it would be possible to adjust it to make it work on Laravel too.

Thanks a lot.

**Comment by barryvdh** [comment]
You can create your own extension. The only thing the extension does, is set some defaults, include a function to call the Kint::dump method and tweak a little.

You can call @Kint::dump($var) to return the output as string, instead of echo'ing it.
I don't know what twigbridge you are using, but with my version (https://github.com/barryvdh/laravel-twigbridge) you can add functions in the config, without creating an extension.

```
'functions' => array(
    'kint' => array(
        'is_safe' => array('html'),
        'callback' => function($var){
            return @Kint::dump($var);
        }
    )
),
```

You can now call `{{ kint(myVar) }}` in your Twig template.
If you need the other functions (trying to determine the variable name etc, I can see if I can fork the extension for Laravel and include it in my bridge. But you can also do that yourself.

**Comment by jnvsor** [comment]
This belongs in an extension. I may write one and add it to this organisation later on.
