### ISSUE TITLE
Doc about how to install Kint globally on PHP

### ISSUE THREAD

**Issue by igorsantos07** [kint-php/kint#111]
I've easily installed Kint on my linux machine by using a custom, global dir for composer (like `/opt`, that I think was meant for that) + the `auto_prepend` feature of PHP. I could send a PR with those instructions if you feel the package should support that :)

**Comment by raveren** [comment]
Sounds very interesting! This should not be part of the main repository though, I'd gladly add it to the documentation:

https://github.com/raveren/kint/tree/gh-pages

it's pending a complete re-write however, but please, elaborate on how you did the install :)

**Comment by dorian-marchal** [comment]
Could be useful :+1:

**Comment by jnvsor** [comment]
This is more PHP documentation than a Kint documentation

**Comment by igorsantos07** [comment]
The fact it's a PHP feature doesn't mean it shouldn't be mentioned in Kint install procedures, given it's a good way to get it installed for multiple projects without having to require it separately in each of them. Otherwise, why bother explaining how to require a Phar if includes are also explained in the PHP docs?

This task and its related PR were closed single-handedly when the doc was already written and tested, but got broken given it was forgotten and other changes further complicate the idea, leaving in my hands to re-re-redo what I had already done.

**Comment by jnvsor** [comment]
If we documented every possible use case the documentation would be so verbose as to be useless. This is too niche IMO

**Comment by igorsantos07** [comment]
We ended up migrating in my current project to dump/dd which already come with Symfony/Laravel helpers (just to reduce dependency weight), and.... guess what? [Symfony does have the exact same instructions](https://symfony.com/doc/current/components/var_dumper.html) I tried adding here, ages ago. I guess it's not _that_ niche, or at least not to a big audience such as Symfony.

![image](https://user-images.githubusercontent.com/532299/157090907-3647c92f-81ce-4b96-b2ae-7823e5487192.png)

**Comment by jnvsor** [comment]
That's probably a really bad idea!

Composer's global is intended for "CLI tools or Composer plugins" (per the composer docs) and there's no telling what kind of unintended side-effects you'll get if you include the global autoloader in your auto prepend. You use composer global to install php-cs-fixer, psalm, composer itself. The kind of stuff you put in your $PATH. Auto prepending your global autoload is basically autoloading the full dependency list of those tools on every run.

This will work by accident in most cases because composer prepends the autoloader by default, so if you have a conflicting package the local one will be loaded first, but it's a really scary proposition to me. Even just for development, since you won't know if your code is depending on a library (Or worse, polyfill) in your global until it breaks when you put it live without it.

**Comment by igorsantos07** [comment]
👀 You're right, that does feel dangerous. Gladly, the instructions I wrote would include the Kint class directly. Not sure if nowadays it needs more than that?

Anyhow, my point was mainly to show this might not be that niche, but given the dust it accumulated, I guess people actively looking for this (if any?) will find it googling.

Best regards!
