### ISSUE TITLE
Split helpers from class and make optional

### ISSUE THREAD

**Issue by barryvdh** [kint-php/kint#114]
A bit similar to #99, I would like it that we could use Kint 'standalone' without side-effects, like registering functions. Especially stuff like s/d/dd/sd which could be common.

What would you think about autoloading the Kint classes (classmapping or psr-4), and creating a seperate aliases.php file. And perhaps add a method `Kint::bootstrap()` or `Kint::loadAliases()` etc, to register the alias functions on demand.

My use-case is laravel-debugbar, which uses Kint for dumping the object in a pretty (plaintext) way, but it conflicts with the default dd/xdebug functions etc. (see https://github.com/maximebf/php-debugbar/issues/121)

**Comment by raveren** [comment]
Hey there!

First of all, I'd like to not autoload the classes in the foreseeable future as PHP5.0+ compatibility is a must IMO and the file structure changes quite rapidly as the tool is still being developed (albeit really slowly in the past couple of months :( sorry, chaotic life nowadays)

I've reworked the configuration from the ground up (still polishing and testing), but have not solved the function alias issues. I'm comfortable with any possible solution, even using `eval` if it comes to it (it's not evil if you know exactly what you're doing) and am still open to any proposals. Again, one of the most important aspect I want to maintain is the _zero-setup_ guarantee so just plopping Kint via any means into your source would provide 99% of users with a working debugger that fits all of their basic needs.

I could create a separate branch without the alias functions I guess..? That would work for you wouldn't it? What would be the side effects for composer users (I still haven't used it :))?

**Comment by barryvdh** [comment]
5.0 support? That would probably make it a bit trickier indeed :P  spl_autoload_register is only available from 5.1.2 (which is from 2005 or something..) But that is your decision of course.

I think you could still make classes autoloaded with Composer, but create a `kint.php` file for the older users, which would require the class.Kint.php and parsers etc. So someone without Composer can just download the files and require that file. And Composer users would just use Autoloading.

But if 'zero-setup' a must, that would make it a bit harder, because when you require it with Composer like you do now, it will load your classes (and configuration etc) directly, so you can't control when it happens (or hook in just before, to change some config). When you use autoloading, it only maps you class, so it would have to call something on the class, before everything is loaded (and the aliases kick in). So `Kint::dump()` would work directly, but `d($var)` wouldn't work until it is explicitly loaded (`Kint::register()` or similar)

I think creating a different branch would be a bit cumbersome to maintain. And perhaps my use-case isn't really big, but I guess it would help to be adapted in frameworks.

**Comment by raveren** [comment]
Autoloading just for the sake of autoloading is silly. Kint manages its files properly, all public methods are in the main Kint file so by the time any of them are called, all required files are loaded...

BTW, there's another related issue a user has been facing (it could be relevant to the debug toolbar too): he uses MULTIPLE instances of kint included by multiple different tools, so I am going to autoload a file with only:

``` php
if (!class_exists('kint')) {
    require __DIR__ . 'kint.class.or how is it named';
}
```

But back to your problem, I'm guessing a branch/fork from stable master with settings adjusted for use as a stand-alone helper (read: non-zero-setup - configuration needs values to work, no aliases etc) would be the most obvious solution. I'd manage to keep it updated, what do you think, would that work regardless it being, as you put it, cumbersome to maintain..?

**Comment by barryvdh** [comment]
But it isn't autoloading for the sake of autoloading. The point is that with autoloading, the class is only loaded when it is needed, so would also work for that users case.

I guess that would work, but that would block users from also using the regular version, because I think you can only require one branch, but I'm not totally sure about that.

In my exact case, I only use the kintLite functionality, so then it would be easier for me to just copy that and not confuse composer too much..

**Comment by raveren** [comment]
Kint class should not be autoloaded IMO, otherwise it takes extra effort on the users part to ensure `d` and `dd` are defined at all times, so either you use Kint and include it everytime (which is negligible resource-wise anyway) or not use it at all. Or am I missing something?

Kint is not your usual functionality, it's a debugger, it acts in ways no other tool would be allowed - all for the sake of comfortability for the developer.

You are correct in saying that the users will have to have their own set of settings than for example a tool they use that also requires Kint. Fortunately, the new settings implementation uses the factory pattern and I'll try to devise a way to differentiate which settings are used by who - most probably the userland code takes the default global settings and vendors have to pass in their settings at call-time - or something. I'll come up with a solution, it's fine.

For the time being, I can branch the WIP branch to bootstrap the official _Kint as a component_ functionality and we can see what can be improved. Would that suit you?

---

Also, FYI, the kintLite function has been long-deprecated in the wip branch for the sake of output-modes. You can now choose between text-only, plain with some HTML sugar, console output and the full-fledged default HTML. All of them have additional sub-modes like console colors which switch on and off automatically by guessing the users intent. Also all of them use the unified variable parser, it's just the final output that differs. It's much more robust and full of improvements since the stable branch.

For now, just use (this will be improved obviously):

``` php
$oldKintMode = Kint::$mode;
Kint::$mode = 'plain'; // or whitespace
$output = Kint::dump($var); // @ modifier no longer a requirement when assigning the result
Kint::$mode = $oldKintMode;
```

**Comment by barryvdh** [comment]
Yeah I noticed the new methods, but as long as they are in WIP (not stable releases) I can't really require them, for people who have minimum stability to stable.
I guess a Kint as component could work, but I'm not sure if it would be a branch or a different repo, or at least a different composer package. The problem would probably be that a user already uses Kint, but wants my tool (which uses Kint component), so it would load both Kint versions at once (or conflict of that's not possible).

**Comment by raveren** [comment]
Well, loading both classes at once would only result in two physical copies of Kint source, but with the aforementioned fix (`if (!class_exists('kint')) { ...`) that would become unnoticeable as long as I enforce 3rd party vendors to only load the configuration-less Kint so that the one the user downloaded and set up in global (settings-wise) code would be used in userland.

So basically, vendors use some sort of dependency injection into Kint (I can realize `Kint::dump()->useSettings($this->_kintSettings)`) and the end-user still is able to use `Kint::dump();` with their settings and everything's fine.

So the path is clear, I think this is the best solution - above combined with two separate repos.

I'll start work on it and it will come along with the long over due v1.0.0

**Comment by jcisio** [comment]
Currently Kint is always loaded with composer, even it is not used. It is because of those lines in composer.json:

```
"autoload": {
    "files": ["Kint.class.php"]
},
```

It's buggy, because it is loaded very at the beginning, so helper functions in global namespace conflict with other libraries, and the check like `if (function_exists('dd'))` is useless.

**Comment by raveren** [comment]
Due to issues like this one, I am renaming the usual offender `dd` to `ddd` - `dd`'s status now is deprecated and I will remove it completely in a couple of months.
