### ISSUE TITLE
The '-' modifier should not clean previous Kint outputs

### ISSUE THREAD

**Issue by lear2012** [kint-php/kint#129]
As the title said, it can clear the output of s() while d() 's output still there.

**Comment by raveren** [comment]
Umm, the title contradicts the description, but anyway the `-` modifier clears _everything_ sent to output up to this point. There's a theoretical solution I might try, but not in the near future.

**Comment by lear2012** [comment]
:) sorry for my explanation, it is just a feature not that urgent, i think. by the way, nice work!

**Comment by jnvsor** [comment]
To quote the docs:

> will clean all previous output to screen before displaying the dump

I think if you want this behaviour it's going to get rather complicated. You might look to the way symfony's VarDumper works - it doesn't print the output at all, but stores it for later viewing in the symfony debugbar.

Since this feature is fairly flaky as it is (Won't work if you're not using OB) I'm going to mark this one out of scope. A better solution would be a "Print output at end of page" handler as seen in #178
