### ISSUE TITLE
Codeigniter - Shows exactly what you dump and where you dump it from.

### ISSUE THREAD

**Issue by osapishchuk** [kint-php/kint#171]
Codeigniter -> Shows exactly what you dump and where you dump it from <- funtionality is not working properly as on my mind. For example I have main controller wich starts like this:

```
<?php if(!defined('BASEPATH')) exit('No direct script access allowed');

class Home extends CI_Controller {

public function __construct() {...
```

This part of code is somewhere(line 177) in index method below:

```
$this->load->library('kint');
$this->kint->dump($this->data);
exit;
```

I expect to see name of the current class and method where I am, instead I see this:

![](http://puu.sh/kfX9d/66fce40102.png)

**Comment by raveren** [comment]
the wrapper is the cause of the problem, but I attempted a fallback-workaround: it will not display the variable name when impossible to detect, please try updating to the latest commit (https://github.com/raveren/kint/commit/9a072e1bda25cf62b809db46b505fb8d4a9dfe6c)

**Comment by osapishchuk** [comment]
yes it's working I forked old version of codeigniter version -> adriangonzales/codeigniter-kint . And he is not updating his fork, algthough on your site that version is official. I will refork his version and will try update Codeigniter version in future(according to your updates) so you could change official version on my git. Thanks any way. And you did nice job.

**Comment by raveren** [comment]
>  I will refork his version and will try update Codeigniter version in future

very cool! Since you're the maintainer now, you can add this line to your wrapper:

``` php
        Kint::$aliases['methods'][] = [ 'your wrapper class name', 'dump method' ];
```

it _should_ allow kint to detect and display the variable name correctly - but this has not been tested as thoroughly as I'd like to (ungh, no test suite :( ) and if it doesn't - please tell me.

Using above command also puts you at a risk of deprecation, as when I increase the version to 1.1 or a later 1.x version, I am going to bring changes to Kint configuration that will not be backwards compatible. However, that will not come soon.

Once you're happy with your fork, let me know and I will change the link to point to yours...
