### ISSUE TITLE
Should view/compiled/kint.js be minified?

### ISSUE THREAD

**Issue by jpeltoniemi** [kint-php/kint#173]
Considering that this is a debugging library, should you really sacrifice readability in favor of file size?

**Comment by jpeltoniemi** [comment]
To be more precise, why serve a minified version and not the unminified /view/base.js?

**Comment by raveren** [comment]
Well there are times when you need to see the source code of the page, and I'd rather the css/js would reside in one line and not clutter up the remainder of the page. 

I don't see any real reason not to do that. If you do, share your thoughts, I will consider them :)

**Comment by jpeltoniemi** [comment]
Sorry for delay.

I needed to change something (can't remember what) from the js. I understand that unminified javascript would clutter the document, but doesn't Kint do that pretty fine on its own if a big object is being debugged? :)

I for one haven't had to look at page source even once while there is Kint output on page. Someone else might though, so how about making the unminified js reside in the same folder and adding an option for deciding which one to use?

**Comment by raveren** [comment]
> an option for deciding which one to use?

There actually used to be a setting for that. Then, after several years of never using it once I removed it in an attempt to minimize feature creep. 

This change is too arbitrary to become a priority (of which are many - mainly updating the friggin project page :( ), but you're free to try to convince me otherwise :) If there's an actual real-world usecase for this, I will implement it, but currently I see none...

**Comment by jpeltoniemi** [comment]
I don't completely agree, but I see your point, and it's more like a matter of preference than of doing things wrong or right :)

**Comment by raveren** [comment]
I don't see how you got that from what I said. It's _precisely_ a matter of doing changes for objective reasons and not because of baseless opinions. 

If you have a real-world reason for the change (any change) you are requesting, I will consider it and if it's a valid concern that has a viable solution, I will definitely implement it, take a look at the discussion in any of the 100+ issues I closed if you don't believe me.
