### ISSUE TITLE
Pods framework objects basically dead lock the kint output

### ISSUE THREAD

**Issue by torian257x** [kint-php/kint#186]
I use

http://pods.io/

when I output their objects, I pretty much freeze my server.

I get a 
`Fatal error: Maximum execution time of 30 seconds exceeded in /home/myhome/dev/kint/parsers/custom/objectiterateable.php on line 10
`

isn't there a possibility to limit the depth to avoid endless loops?

**Comment by torian257x** [comment]
i wish i could give you the version number i used but i dont seem to find it

**Comment by torian257x** [comment]
is there something i can help you with, say for setup of a testcase?

**Comment by jnvsor** [comment]
This is just a standard timeout because your objects are so big it takes more than 30 seconds to debug and print them out. If you change your server config to have a larger (unlimited) timeout it should work. That said, if you're already hitting 30s most likely whatever you're debugging must be freaking huge - you can change `\Kint::$maxLevels` to get a shallower debug.

**Comment by raveren** [comment]
I implemented a `Kint::$maxLevels` counterpart for single-level object limit, I will release it soon-ish, stay tuned.

**Comment by jnvsor** [comment]
@Jossnaz can you see if the blacklist plugin in [2.x-dev](/kint-php/kint/tree/2.x-dev) solves your problem?

**Comment by torian257x** [comment]
i now typically use this:

```
    include_once '/home/jossnaz/dev/kint/Kint.class.php';
    \Kint::$maxLevels = 4;
    \Kint::dump( $podsObject  );
    die("bb");
```

solves the issue, eventually need to upstep the levels to see the data

**Comment by jnvsor** [comment]
Well 2x will help you there - the access paths will show you exactly what you need to debug the second time around :)

Can I close this?
