### ISSUE TITLE
'Called from' line shows Kint's code, rather than the caller

### ISSUE THREAD

**Issue by joachim-n** [kint-php/kint#193]
When I output a variable with Kint, the 'Called from' line says:

> Called from <ROOT>/mysite/web/modules/devel/kint/src/Plugin/Devel/Dumper/Kint.php:51 [Drupal\kint\Plugin\Devel\Dumper\Kint->export()]

It should show me the file where I actually requested the output.

The full backtrace starts like this:

```
<ROOT>/mysite/web/modules/devel/src/DevelDumperManager.php:85 [Drupal\kint\Plugin\Devel\Dumper\Kint->export()]
<ROOT>/mysite/web/modules/devel/src/DevelDumperManager.php:95 [Drupal\devel\DevelDumperManager->export()]
<ROOT>/mysite/web/modules/devel/devel.module:345 [Drupal\devel\DevelDumperManager->message()]
<ROOT>/mysite/web/modules/devel/devel.module:375 [dpm()]
<ROOT>/mysite/web/core/modules/views/src/Plugin/views/relationship/RelationshipPluginBase.php:180 [dsm()]
```

This is using Drupal's Devel module. As you can see, there are a few function calls between the place where I call it using dsm() and the actual call to Kint.

Is there something that Devel should be passed in to Kint->export() to tell it how many items to remove from the backtrace()?

(Corresponding issue on Devel: https://www.drupal.org/node/2643392#comment-11060295)

**Comment by raveren** [comment]
Unfortunately I am not the owner of the drupal fork and I don't even know what the `export` method does, but `Kint::_stepIsInternal` method is responsible for defining how many steps to roll back and show the true caller in the trace...

**Comment by joachim-n** [comment]
Oh heck, is the Kint code inside that module a fork? Urgh :(

**Comment by raveren** [comment]
That's actually my fault, I was unresponsive to their change requests, but it required a heavy rewrite so I didn't find the time sadly...

**Comment by jnvsor** [comment]
> That's actually my fault

Not really. I've been working on a kint extension to bolt/bolt and all I have to do to get decent traces is add my entry function to `\Kint::$aliases`

@joachim-n I suggest you raise this as a bug report on the devel module

**Comment by joachim-n** [comment]
So is the right way to do this just to add to Kint::$aliases before calling Kint::dump(), like this:

```
      Kint::$aliases += [
            'dsm',
            'dpm',
            'kprint_r',
      ];
      $output = $return ? (isset($name) ? $name . ' => ' : '') . @d($input) : Kint::dump($input);
```

I filed this on Devel. I'll report back there with the information here.

**Comment by jnvsor** [comment]
@joachim-n Well if you do that it'll nuke 3 values that are already in the array - you need to `array_merge` or just append one at a time.

**Comment by willzyx-dev** [comment]
@raveren first of all thanks for your great job on this library :)
The `devel/kint/src/Plugin/Devel/Dumper/Kint.php` is not a fork of the lib but simply an adapter (devel has a pluggable dumper system that allows you to choose between different libraries for dumping variables). `Drupal\kint\Plugin\Devel\Dumper\Kint->export()` internally simply call `@\Kint::dump($args)`;

The big downside of use \Kint::$aliases is that you loose the modifiers functionality and for this reason it is not used in devel. For example:

```
function a($args) {
  return b($args);
}

function b($args) {
  // set our functions as a kint alias
  \Kint::$aliases['functions'] = array_merge(\Kint::$aliases['functions'], ['a', 'b']);
  // return the string representation of the variable 
  return @\Kint::dump($args);
}
```

if you call a($args) the @ modifier used in b()  is completely ignored and kint dump the variable instead of return the output

**Comment by jnvsor** [comment]
@willzyx-dev Please pay attention - `devel/kint/kint/Kint.class.php` is clearly a fork.

Additionally, your example makes perfect sense - The entire point of modifiers is that they are used in the _calling_ function - if you set `\Kint::$aliases` and your user calls `@a($var)` the modifier will be used.

If you simply want to alter behaviour inside the helper function then use the `public static` fields like `$returnOutput`. That's what they're there for.

**Comment by willzyx-dev** [comment]
@jnvsor only for clarity `devel/kint/kint/Kint.class.php` is NOT a fork. Is an old version of the library (commit [7a8ae07](https://github.com/raveren/kint/commit/7a8ae071f68e233fffe1bc486ef5208dc26919f2))

I see your arguments but since devel is not "kint-centric" we cannot force our users to use @ when they use the devel functions.

\Kint::$returnOutput can be a viable solution, thanks for the hint, but as you can see this property not exists in the version that we use

We will consider to update kint to the latest version
Thanks
