### ISSUE TITLE
Better recursion to non-direct precedents handling

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#204]
Steps to reproduce:

```
        $a   = [ "Array a" ];
        $b   = [ "Array b" ];
        $a[] = &$b;
        $b[] = &$a;
        $c   = [ &$b ];

        s( $a );
        s( $b );
        s( $c );
```

Output:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                      $a                                      │
└──────────────────────────────────────────────────────────────────────────────┘
array (2) [
    string (7) "Array a"
    & array (2) [
        string (7) "Array b"
        & array (2) *RECURSION*
    ]
]
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Called from <redacted>

┌──────────────────────────────────────────────────────────────────────────────┐
│                                      $b                                      │
└──────────────────────────────────────────────────────────────────────────────┘
array (2) [
    string (7) "Array b"
    & array (2) [
        string (7) "Array a"
        & array (2) *RECURSION*
    ]
]
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Called from <redacted>

┌──────────────────────────────────────────────────────────────────────────────┐
│                                      $c                                      │
└──────────────────────────────────────────────────────────────────────────────┘
array (1) [
    & array (2) [
        string (7) "Array b"
        & array (2) *RECURSION*
    ]
]
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Called from <redacted>

```

`$c` output is wrong; the parser engine needs an object reference map, it now assumes all references are one and the same entity (which, to be fair, usually is true).

**Comment by jnvsor** [comment]
I've mentioned before that I think this can't be done the way you're thinking of - and I'll attempt to explain it again here.

## The problem

Let's take a very simple example: We have an array who's only element is a reference to itself:

``` php
$a = [];
$a[] = &$a;
```

This can be visualized like this:

![](http://i.imgur.com/JMTIQFc.png)

Now, lets make a copy of this array and see what we're looking at:

``` php
$_a = $a;
```

This can be visualized like this:

![](http://i.imgur.com/6HUxiHZ.png)

Now you can see, it actually _does_ take 2 redirects before it hits recursion.

Because kint takes parameters by value, the implicit copy will be done to every array passed into kint. This is what causes the initial problem of kint having to go through the array twice to find the recursion - the first time it's going through a copy, so it's not actually recursing yet.

It doesn't affect objects since they are passed by reference by default, and it doesn't affect arrays below the root since they aren't copied, their _references_ are copied. This is why this bug only appears if the toplevel array is the one being referenced.

## Check if it's the same data

The obvious solution is to pass the object by reference, but there are multiple problems with this.
- You lose the ability to use `func_get_args()` so you have to flood the function definition with parameters
- You can no longer debug constants

Obviously this isn't going to work, so the next best thing is to check if the arrays look the same. (Which is what kint tries to do today)

## Check if it _looks_ like the same data

Unfortunately, there's no way to distinguish values from references in PHP, so we have to store the entire structure of the toplevel array and compare it against every child array we come across.

We also have to do this with the flawed recusion handling or we'll run out of memory. Even built in PHP equality gives you "_**Fatal error**:  Nesting level too deep - recursive dependency?_" - you'd think they'd have something for that but no!)

This could be done with a second parser (I dread to think!) but lets just use `print_r` as an example here: We now have to store the `print_r` of the toplevel array, and then run a `print_r` on every child array recursively and compare the output with our stored output.
- This will take a long long time
- This will eat a lot of memory (I know for a fact `print_r` output can go over a gig in zend)
- This won't help in an example where we actually do want to debug `$_a` since it will incorrectly assume it's an `$a` that's been copied by the function call

Unfortunately looking at the technical limitations and the fact it still won't work in edge cases, this isn't viable either.

IMHO the default PHP behaviour of showing the extra recursion is the most correct you can expect.

### A third option

As I write this I've come up with another potential way to fix this, but it's hare-brained and probably won't work so take it with a bag of salt:

If we hit a recursion point we should be able to repeat the access path up to that point to hit it again. Prototype:

``` php
$a = ['a' => ['b' => []]];
$a['a']['b']['c'] = &$a;

$b['a']['b']['c'] = [4 => &$a];

$c = ['a' => ['b' => ['c' => &$a]]];

function recursion_prototype(&$var, $path, $num_checks = 20){
    $lastvar = $var;
    for ($i = 0; $i < $num_checks; $i++){
        if (!$lastvar = eval('return isset($lastvar'.$path.') ? $lastvar'.$path.' : null;'))
            break;
    }

    if ($lastvar)
        echo "Recursion!\n";
    else
        echo "No recursion!\n";
}

recursion_prototype($a['a']['b']['c'], "['a']['b']['c']");
recursion_prototype($b['a']['b']['c'], "['a']['b']['c']");
recursion_prototype($c['a']['b']['c'], "['a']['b']['c']");
```

Of course this would need eval to work (yuck) - but it would detect "apparent" recursion without needing to store a huge `print_r`.

All that said I still believe the default PHP behaviour is both correct and preferable: as the third example shows, arrays that just happen to have the same contents will incorrectly determine recursion.

**Edit:** I've gone ahead and implemented this method in a branch off 2.x-dev: https://github.com/jnvsor/kint/commits/2.x-dev-recursion

This should be the behaviour you're expecting, but it still suffers from the problem of the edge case where you want to debug an identical but "Higher" recursing array. This may be a moot point but I'd like to have a confirmation before I go and start adding it to 2.x proper

**Comment by jnvsor** [comment]
While this is theoretically doable with PHP 5.6+ `...&$opts` syntax, this precludes the use of literals when dumping. That's not going to work. I'm going to close this as wontfix for now as it seems to be impossible to achieve with current PHP implementations.
