### ISSUE TITLE
Some (implemented) extensions that you could integrate

### ISSUE THREAD

**Issue by jthomaskerr** [kint-php/kint#21]
Hi,

I like your tool. I'm currently using it with ASTs so there is a lot of recursive noise. As such I've added a few features that make life a bit easier:

-- color coding and hyperlinking recursive references
-- filter based on property name or class name (this could be further generalised)
-- filter statics
-- filter null values.

I'd be honoured if you'd include my additions in your codebase. What do I need to do to be able to initiate a pull request?

![Screenshot](http://oi49.tinypic.com/2w2fzw8.jpg)

Joe.

**Comment by raveren** [comment]
Woah that's friggin excellent, most of these features have been previously submitted in the issue tracker, your work is simply great!

One way to contribute is to fork the github code, merge your changes in and create a pull request from that, I'm not a git superuser yet, sorry. 

If you don't want to go through the trouble, you can send the code to me and I'll happily merge it for you, but I'd be happy if you could make a pull request from your own account so that you would be automatically credited for your work.

**Comment by raveren** [comment]
so how could I get a peek at the code? :)

**Comment by raveren** [comment]
Hey, Joe, could I have a look at your changes, I will implement them into the current build and will credit you appropriately. Thanks!

**Comment by jthomaskerr** [comment]
Hi there,

Apologies for missing your emails. I'll fork and create the request
immediately

Joe.

**Comment by ptim** [comment]
wow.. looks awesome - would love to see this!

**Comment by raveren** [comment]
This is referenced from #24, I still have to rethink recursion display to have the best of both worlds (recursion does not always mean that both objects are identical). Thus I'm leaving #24 open.
