### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by AdamPS** [kint-php/kint#230]
Lots of useful commits since last release in 2015, so it would be great to have a new release if possible please.

**Comment by jnvsor** [comment]
Please look at [kint-php/kint](https://github.com/kint-php/kint/)

It was supposed to be a placeholder until @raveren got back but he's taking his time so i'm probably not going to wait - at least with asking for 2.x feedback

**Comment by raveren** [comment]
I'm sorry for the wait, kint is now under its own github organisation, happy coding!

**Comment by jnvsor** [comment]
@raveren Nice timing! Mind transferring ownership so I can actually push? :)

**Comment by AdamPS** [comment]
Wow that was fast, thanks everyone!  [raveren/kint] is now redirecting to [kint-php/kint] so maybe that means the transfer has been done?

**Comment by jnvsor** [comment]
Ok so it looks like @raveren had internet access just long enough to transfer the repository but forgot to make me owner and redirect the old packagist package.

So now we're in a bit of a bind with a potentially broken composer package and a repo that no-one can push to - despite my having nearly 200 commits and 2 tags to push.

Last time @raveren had internet access was 2 months ago. I really hope he's back to fix this in less than 2 months this time... Could just be he's gone to sleep since it's after midnight where he is.

In any case let's not panic 'till morning :/

In the meantime - if anyone wants to help test 2.0-alpha1, please go to [jnvsor/kint](https://github.com/jnvsor/kint/releases/tag/2.0-alpha1)

**Comment by jnvsor** [comment]
Looks like @raveren came back and made me owner. Yay!

I'll get to work when I come back from work in about ~11 hours. In the meantime I've pushed the tags for you

**Comment by AdamPS** [comment]
Excellent, thank you both very much.  The ongoing development is a big help to the Drupal 8 community and other users.  I have updated 

I can see the tags, thanks.  It looks like the task of creating corresponding releases is still to do as part of your next chunk of work.

**Comment by jnvsor** [comment]
Yes it's on the todo list - I haven't worked with Drupal in a few years. Is Kint part of Devel or Drupal core? (Or part of Devel which is part of Core?)

**Comment by jnvsor** [comment]
Releases have filled in (And the branch has been created: [2.x-dev](/kint-php/kint/tree/2.x-dev)) Please test and give feedback, thanks!

**Comment by AdamPS** [comment]
Great thanks.

In Drupal 8, Kint is a sub-module of devel which is a separate module, not part of core.  The kint library lives at modules\devel\kint\kint.  I have raised [an issue](https://www.drupal.org/node/2859114) to ask the module maintainers to take your new release.

**Comment by jnvsor** [comment]
Ah, I was under the impression that devel had become part of core. Guess I was wrong
