### ISSUE TITLE
dump not showing class properties - possibly issue with abstract/extended/child classes?

### ISSUE THREAD

**Issue by Yuuseki** [kint-php/kint#232]
Hey,

so while developing for wordpress, I encountered an incomplete dump issue when I used PHP's DOMDocument class to load an HTML description of a wordpress post.
[DOMDocument class](http://php.net/manual/de/class.domdocument.php), which extends [DOMNode](http://php.net/manual/de/class.domnode.php)

in my code, first:
```php
$dom = new DOMDocument;
$dom->loadHTML('<?xml encoding="UTF-8">'.$category->description);
```

later:
```php
<pre><?php var_dump($dom); ?></pre>
<?php !Kint::dump($dom) ?>
```

The output I got - kint:
[http://i.imgur.com/60rooDE.jpg](http://i.imgur.com/60rooDE.jpg)

var_dump():
[http://i.imgur.com/uvsogVu.jpg](http://i.imgur.com/uvsogVu.jpg)

as you can see, var_dump() dumped properties, while kint didn't dump any properties at all and only gave me methods. var_dump() also dumps properties of the parent class DOMNode.

Not sure what's the problem here, possibly related to object inheritance?

**Comment by jnvsor** [comment]
The DomNode system is a hell of a beast. Because it has some 10 properties all of which can recurse into itself, dumping a small domdocument would crash your browser (And possibly your server too!)

Because of this, PHP has a lot of tricks in place hardcoded to prevent anyone going too deep into the DomDocument. Hence all the `(object value omitted)` instead of values in `print_r`/`var_dump`.

This dirty hack to save you from yourself also applies to the reflection and casting systems - casting a domdocument to an array will give you an empty array instead of the properties you are supposed to be able to see, and reflection will tell you a domdocument is empty.

However, if you know the properties ahead of time (And we do) you can loop through them and access them explicitly to build more-or-less the property list of a domnode.

This is what the DomNode plugin in 2.0-alpha1 does. Because of the aforementioned recursion issues, simply dumping everything would absolutely crash your server, so the plugin comes with a configurable blacklist of properties and only shows children by default (So you don't get the same information thousands of times over through the parent/sibling/etc)

It's still far slower than the simplexml one but it's the best you can hope for, honestly.

Please try out 2.0-alpha1 and give feedback if you find any bugs (I know DOMNode is one of the places I expect there are tons of them hiding)
