### ISSUE TITLE
Why removing dd() and ddd() ?

### ISSUE THREAD

**Issue by steevanb** [kint-php/kint#238]
In 1.x version, `dd()` (deprecated) and `ddd()` calls `d()` then `exit`.
It was a nice shortcut ! Most of the time, i use `ddd()`.

Why removing this shortcut in 2.x ?

**Comment by jnvsor** [comment]
Because it's easy enough to just type out `die;`. More importantly, because it only takes 4 lines to make it yourself, not worth polluting the global namespace for that. See #236 for an example

**Comment by vesper8** [comment]
I find it super annoying that you removed ddd(). Typing an extra die() means it's on a second line when using auto-code-formatting means I have to comment out two lines instead of one line when debugging

Tons of people were using ddd and now it's caused confusion, and the documentation for re-adding ddd are poor and confusing and don't work easily in Laravel. I don't want to have to add a composer autoload just for this!

**Comment by jnvsor** [comment]
> the documentation for re-adding ddd are poor and confusing and don't work easily in Laravel. I don't want to have to add a composer autoload just for this!

@vesper8 Those instructions are for PHP. They work with or without composer or laravel. Defining functions in your framework of choice is way out of scope for Kint.

**Comment by kktsvetkov** [comment]
Perhaps include a file (like "legacy.php") which will declare these functions again, and whoever needs them can just include the file. It is optional, so only people that need it will include it. Best of both worlds.
