### ISSUE TITLE
how to add new function to helpers?

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [kint-php/kint#256]
hi

tanx for good package

how can I add new function as helper function without edit source file of library (init_helpers.php)?

**Comment by jnvsor** [comment]
Have a look at the [documentation](https://kint-php.github.io/kint/advanced/#helperfuncs)

**Comment by Mehrdad-Dadkhah** [comment]
@jnvsor 
yes I do that before and I test it  in laravel.
my problem is that in composer autoload_files.php init_helpers.php load before laravel helpers and so it's work fine, but when I define dd() function and add it to Kint::aliases I have redeclare function error because laravel helper define dd() function before and my target is to overwrite it.
If I can overwrite init_helpers.php and in init.php can load another init_helpers.php (with some configs) my problem resolve ...

**Comment by jnvsor** [comment]
No, that won't resolve your problem, it'll just cause a fatal error when laravel tries to define dd instead. Your conflict is an issue with laravel, not Kint. I don't know if there's a way to remove dd from laravel without creating a merge hell (I doubt it) but in either case your best option is to use a different name. (Kint 1 added `ddd` specifically because of the conflict with laravel)

**Edit:** A quick grep shows modern laravel defines dd [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/helpers.php#L517) - It's got a defined check so if you really want your dd defined first you'll want to stick it in your composer [autoload](https://github.com/laravel/framework/blob/master/composer.json#L89) or some other part of the code that's called earlier than this code.

**Comment by Mehrdad-Dadkhah** [comment]
Thanks you for reply @jnvsor 

Yes, I know that my conflict is with laravel and because in composer auto load helpers.php of laravel load faster than my helper.php (where I define dd function) and my target is overwrite laravel dd. But if I can change path of init_helpers.php of kint and load another init_helpers.php my problem will be fixed.
for example if I can change KINT_DIR as result it will load another init_helpers.php (my helper file instead of kint helper file)

I point to here:

```
require_once KINT_DIR.'/init_helpers.php';
````

If we make KINT_DIR optional, Kint will be more flexible.

**Comment by jnvsor** [comment]
No. `KINT_DIR` is integral to... Well a whole lot of stuff. I won't bore you with the details but that's not the way to do this. Even if it was, how exactly were you planning on doing that? Set a global or define before calling composer? Because as soon as composer is required the autoload on laravel is going to trigger too, and without composer you don't have Kint either.

Even if you did insert your code into `init_helpers` it would break if you so much as reordered your composer requires. If you must use `dd` then you can make a local composer package and sandwich it between kint and laravel (And now you have an extremely order-sensitive composer.json - yuck)

Just name it `ddd` or something. IIRC `dd` from laravel uses symfony's vardumper which is a nice compliment to kint anyway.
