### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#26]

**Comment by jnvsor** [comment]
There's a test suite in the form of some basic TravisCI sanity (and code style) checks but the architecture of 2.x gives us plenty more in the way of testability.

As for feature demo - I've already tested and can confirm that you can dump a Kint render in a file and display it on a static site such as github pages so that will ideally provide a live feature demo that's easier to access than a test suite.

**Comment by jnvsor** [comment]
We have an actual test suite now! (Yay!)

Now all we need to do is write tests!... Yuck that sounds boring. I'll do it later. (Probably)
