### ISSUE TITLE
Way to keep output outside of page layout

### ISSUE THREAD

**Issue by emahuni** [kint-php/kint#262]
This is the simplest and best php debugger I have seen that does things simple and requires very little effort. Sometimes in the middle of a project you don't want to concentrate on things that have nothing to do with the project and this piece of code does it pretty simple. I loved it.

However, i think it can do very well if there was a way to do what https://github.com/barbushin/php-console does, instead of messing with the output of the running script. These tools are fine, but old. I think this should be implemented.

**Comment by emahuni** [comment]
another way could be to just create a popup window using javascript and use the id of the window to output stuff. This is by far the simplest way to implement this.

**Comment by jnvsor** [comment]
I don't really like the idea of a chrome extension. It would have to be maintained for multiple browsers in multiple versoins in addition to multiple PHP versions.

> another way could be to just create a popup window using javascript and use the id of the window to output stuff

You'd still be altering the output if you did that. I'd prefer a "purer" way of handling it.

You'd also need to store the output somewhere first. This is what symfony/var-dumper does when you have the debugbar installed.

Since it's *fairly* easy to make your own renderer (There's [a simple js one here](https://github.com/kint-php/kint-js)) it would probably be easier to write a renderer that wraps `Kint_Renderer_Rich` and stores it in the same way that symfony/var-dumper does. That would work great for systems that use the debugbar. (Which is everything based on symfony components. Symfony. Bolt. Laravel. Etc)

Alternatively you could tweak the renderer to stick your debug info at the bottom of the page with `register_shutdown_function` or some such.

Any thoughts?

**Comment by jnvsor** [comment]
@emahuni Take a look at the next branch - 3076ae092284c3746fd98dd2383d67f03d6c58e9 - I've added (And made default) a mode that moves the kint dumps to a foldout at the bottom of the page. It won't help if you dump inside script or style tags or something, but it will handle most cases of a dump affecting page layout
