### ISSUE TITLE
Use __debugInfo

### ISSUE THREAD

**Issue by vita10gy** [kint-php/kint#265]
Am I missing some way to use the results of __debugInfo, if provided, when dumping an object?

**Comment by jnvsor** [comment]
Not implemented. Should be easy enough. Are there many libraries out there that implement it? I haven't noticed any myself

**Comment by vita10gy** [comment]
Not sure. I added it in a custom library when I went to look if there was a way to trim irrelevant crap for dumping an object, got all excited with a test print_r becoming helpful again, and then was bummed to see kint just kept on trucking with reflection, or however it's doing it's thing. 

If nothing else it's now a fairly large departure from the default behavior of var_dump

**Comment by jnvsor** [comment]
Well I wouldn't want to stop the other plugins from running just because it found a `__debugInfo` anyway, so if that's what you're after you're better off writing your own plugin. Should only be 50 lines or so. (Specifically, see the "Halting the parse" and "getTriggers" sections in the [writing a plugin](https://kint-php.github.io/kint/writing-plugins/) docs)

A quick grep shows `__debugInfo` isn't present in either symfony or laravel, and that covers a fairly huge part of the PHP marketplace, so I don't think I'm going to implement it
