### ISSUE TITLE
gzuncompress(): data error in kint.php on line 172

### ISSUE THREAD

**Issue by TLMcode** [kint-php/kint#275]
Lately when ever I try to call kint's class function d() on new server installs I often get the error message:
`Warning: gzuncompress(): data error in kint.php on line 172

Fatal error: Call to undefined function d() in test-kint-call.php on line 7`

I've read that the gzuncompress() function is outdated and it can trigger fatal errors on newer server configurations. Obviously I can't edit the obfuscated kint source to try other gzip decompression functions. This has also happened on client shared servers where I do not have root access so I can't update any ini or configs.

From what I've read gzdecode() should be used instead.

Is there any way this can be fixed or is there something I'm missing?

Thanks for any help.

**Comment by jnvsor** [comment]
Hmm - I presume you're putting the file on the server via FTP? Can you try transferring in binary mode?

I just downloaded the raw file from master with wget and ran it under 7.2 and it worked fine, so I don't think that's the problem

**Comment by TLMcode** [comment]
Will do... oddly enough, when I try referencing kint from certain directories, it does work.. I will try to upload in bin mode and report back...

**Comment by jnvsor** [comment]
That sounds... Really weird... Anyway, the file I have here is md5 `70de6386507bed4bd941c9e84f7dc5ea` if you want to confirm via shell

**Comment by TLMcode** [comment]
Setting my ftp client to binary mode fixed this issue. Any ideas why this would happen?
Also, should I be using binary mode all the time? Thanks for any info.

**Comment by jnvsor** [comment]
PHP files are typically text - so ASCII mode should be plenty to transfer stuff. However, the kint 2 build file contains a large binary string that's evalled so that I could fit it all in one file and still support 5.1 (Which doesn't support phar files) so you have bytes in there that flat out can't be represented with the limited ASCII set. (Typically your FTP client will automatically pick binary for images and ASCII for text but it got confused by a php file with binary data in it)

Additional differences are that ASCII mode will change line endings when you send files between windows/unix.

Since ASCII mode is only 12.5% lower bandwidth use than binary I personally always use binary to prevent issues like this one. I'd rather have my files show up on the server exactly the way I made them.

Glad I could help

**Comment by TLMcode** [comment]
Ahhh that makes total sense thanks!!
