### ISSUE TITLE
Allow overriding static methods with LSB

### ISSUE THREAD

**Issue by McSodbrenner** [kint-php/kint#283]
`d()` without an argument just returns "No argument" so it is not really used.
So why not using `d()` for the debug backtrace because it feels more intuitive than `d(1)`

**Comment by jnvsor** [comment]
It's an idea. I can imagine someone accidentally doing an empty dump and freaking out because the page takes too long to load, though.

From an architectural point of view, I would actually like to get rid of that entirely and just tell people to rely on `Kint::trace()` or `d(debug_backtrace())` explicitly. It tends to not work if kint can't access the call point for instance (When dumping from inside an eval or something)

I'm too close to 3.0 to make a big change like that now, but I'll leave the issue open until I decide what to do with it.

**Comment by jnvsor** [comment]
Theoretically this should be easy to implement yourself in kint 3 if you override `Kint::dumpAll`, but since we only support 5.3 we can't use LSB like `new static()`.

We could do it in a roundabout way with `get_called_class` but I'm not sure what the implications of that are. I'll poke around with it for 3.1

**Comment by jnvsor** [comment]
There are 39 different uses of self in `Kint\Kint` - I don't think it's smart to move them all to `get_called_class` just yet. I'm going to leave this up as a potential 4.0 feature, when minimum php version will probably be bumped to 5.6 or something like that.

**Comment by raveren** [comment]
Sorry, but I disagree with this change, sometimes I use a kint+die shorthand as a better `die`. 

Blurting out the whole stacktrace without the users explicit instruction is unintuitive and can crash the page in heavy systems.

**Comment by jnvsor** [comment]
@raveren Yes as I wrote earlier I'm not going to make it do this:

> I can imagine someone accidentally doing an empty dump and freaking out because the page takes too long to load, though.

I left this open because if we ever bump the PHP requirement to 5.5 (? Whichever version had late static bindings) we can make static calls customizable. I'll change the title to prevent confusion

**Comment by jnvsor** [comment]
LSB facade is now on master, and `d(1)` has been removed in favor of `d(debug_backtrace())` and `Kint::trace()`
