### ISSUE TITLE
Not able to view mysqli_connect result

### ISSUE THREAD

**Issue by Norm6257** [kint-php/kint#290]
Hi.. if I assign a mysqli_connect and then try to view it with kint I see everything set to null.  However, if I do a var_dump on it then I see the values.

`
    $dbTest = mysqli_connect($dbinfo['host'], $dbinfo['username'], $dbinfo['password'], $dbinfo['name']);
    d($dbTest);  //returns null for all properties
    var_dump( $dbTest);  //shows values for all properties
`
![image](https://user-images.githubusercontent.com/43974318/46639347-4874c300-cb1a-11e8-9a67-8d04c0d1515c.png)

**Comment by jnvsor** [comment]
That's interesting. I'll take a look later

**Comment by jnvsor** [comment]
So it looks like because `Mysqli` is a proxy for a `resource` (An external C library in PHP) it behaves similarly to the DOMNode system. Of course, it's a little bit different because of course it is.

When casting to array we get all of the properties, but they're filled with nulls since the actual properties are presumably proxies of C level function calls. The solution is to manually request all of the properties directly once we know which properties we want.

Of course it's still not that easy: PHP throws a warning every time you try to access a property when the connection failed, so you need to access `connect_errno` first.

Of course it's still not that easy, because `new Mysqli()` will have a `connect_errno` of 0 just like a working connection.

In the end the only value we can check to see if it's connected or not is `stat`...

Anyway, I've written a plugin to do all of this. Just need to finish writing the tests and I'll add it as an opt-in plugin (Most frameworks these days use PDO as the underlying driver)

**Comment by jnvsor** [comment]
I'm having some trouble finding out whether or not a Mysqli object is actually connected to a server or not. When it's not connected accessing most of the properties throws a warning, and we can't have that in debug code, so I'll need a way to work around it.

**Comment by jnvsor** [comment]
I've added a MysqliPlugin in e6a36b4. It's *not* on by default since most frameworks I know use PDO as the underlying database API, but you can add it like any other plugin: `Kint::$plugins[] = Kint\Parser\MysqliPlugin::class;`

Fun fact: var_dump is *wrong* when it comes to mysqli objects. It has special case code to handle resource objects like this and `DOMNode` but it shows uninitialized properties on `Mysqli` to be `false` instead of `null` (Which they are)

@Norm6257 Can you try out master and see if it's working for you?

**Comment by Norm6257** [comment]
Hi... Really sorry that this has turned into such a bother for you.  Yes, I'll give this a try... I'll see if I can get it done tonight and give you some feedback.

**Comment by jnvsor** [comment]
Oh don't be, this sort of stuff *should* be in kint at some point. And now I learn obscure tidbits about mysqli objects too :)
