### ISSUE TITLE
handle output buffering filters

### ISSUE THREAD

**Issue by beppe9000** [kint-php/kint#296]
When I have such a filter in place Kint's script stops working, preventing the use of '+' and '-' signs.
```
$cb = function ($foo) {return nl2br($foo);};
ob_start($cb); ob_implicit_flush(true);
$a = [[0],[1]]; d($a);
```

I don't know if this can be actually fixed but I report it anyways.
One solution I can think of would be to somehow bypass the buffering layer on demand.

**Comment by jnvsor** [comment]
Yeah that's putting `<br />` tags into javascript code, making it go boom. It *does* actually work with the `-` modifier, since the first thing that does is clear all output buffers.

I don't think this should be considered a bug in Kint since this code has the potential to break anything that outputs newlines.

What are you using this for incidentally?

**Comment by beppe9000** [comment]
I become lazy when debugging php cron jobs in a browser and use that to automatically get `<br />` after newlines. but I think there may be someone else may have more advanced uses of buffer filtering than that :)

**Comment by jnvsor** [comment]
Yeah but that's mostly stuff like "Log to a file" or "Gzip output" or something. It's not something to be used lightly. The most drastic change I can find is symfony replacing the session ID for security purposes.

In any case, standard Kint output uses `white-space: pre` for long texts so that it can be easily copied, so in retrospect this wouldn't work anyway. I'm definitely not going to attempt to make kint withstand arbitrary output meddling.

I'm going to close this. If you use kint for debugging then it will automatically output text and newlines in cli and html in browser, so if you just want to be lazy and debug just use kint :)
