### ISSUE TITLE
Tabular array display kicks in with non-scalar values

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#308]
![image](https://user-images.githubusercontent.com/364220/54680144-c994a500-4b11-11e9-886c-bbdc67bba671.png)

I mean I *can* view the contents of the array, but it feels like a bug

**Comment by jnvsor** [comment]
The problem here is that I frequently have tabular data where 1 or 2 columns is an array or an object. Losing the tabular display just for that really sucks.

If we wanted to check each element (Against a percentage limit for instance) we'd probably kill performance when generating tables too. Any other ideas?

**Comment by raveren** [comment]
the goal is to not make it feel like it's a bug :) I think the main problem is that the arrays are not expandable in the table maybe

**Comment by jnvsor** [comment]
Yeah I briefly considered having it swap tab to contents and unfold the correct element when you click on one of those, but the implementation would be a pain so I pushed it to the back of my mind.

**Comment by raveren** [comment]
maybe if Kint just displays top level variable with rich renderer and it expands into simple display mode, but I don't even know if that's in the realm of possibility 🗡
