### ISSUE TITLE
PHP 7 namespace error: 'object' is a reserved keyword

### ISSUE THREAD

**Issue by nrparsons** [kint-php/kint#321]
I'm getting several of these namespace errors from classes in kint/src/Object:

```
FILE: [redacted]/vendor/kint-php/kint/src/Object/TraceObject.php 
----------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE 
--------------------------------------------------------------------------------------------------------
26 | ERROR | 'object' is a soft reserved keyword as of PHP version 7.0 and a reserved keyword as of PHP version 7.2 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
```

**Comment by jnvsor** [comment]
It's true that object is reserved for typehinting, and because of that you can't use it as the name of an interface or class. However, this only affects namespaces if you try to use it directly:

```php
class Object {} // Error
namespace Object { class X {} } // OK

use Object; // Error
new Object\X(); // OK

use Object as X; // OK
new X\X(); // OK

namespace Y\Object { class X {} }

use Y\Object; // Error
new Y\Object\X(); // OK
```

So [this produces no errors in any version of php from 5.3 up](https://3v4l.org/2KDtd)

Where are you getting this error from? It sounds to me like you have some static analysis running that's a bit too up-tight. If your IDE is running static checks you should probably tell it to ignore `vendor` anyway.

**Comment by nrparsons** [comment]
Thanks, @jnvsor. I was passing this along from a user of a plugin I maintain which includes Kint - not sure exactly how he was getting that error. I'm not seeing the error anywhere myself so I'll close this - just wanted to make sure there wasn't something more at play that I was missing. Thanks for your help!
