### ISSUE TITLE
Parser fails when reading non-initialized typed properties

### ISSUE THREAD

**Issue by element-code** [kint-php/kint#351]
In this case it's the `ClassStaticsPlugin` Parser which seems to handle my `Typed static property` wrong (`Typed static property className::$property must not be accessed before initialization`).
```txt
#1 VENDORPATH/kint-php/kint/src/Parser/ClassStaticsPlugin.php : 95   —  ReflectionProperty->getValue () 
#2 VENDORPATH/kint-php/kint/src/Parser/Parser.php : 585   —  Kint\Parser\ClassStaticsPlugin->parse ()
#3 VENDORPATH/kint-php/kint/src/Parser/Parser.php : 520   —  Kint\Parser\Parser->applyPlugins () 
```

**Comment by jnvsor** [comment]
Hi @element-code - I've fixed the crash in 595c7690c0085338a19b99f9f2dada9f5111655a but I never considered uninitialized statics before and this brings a few new questions.

We determine the (instance) properties of an object by casting it to an array. We deliberately avoid reflection for 3 reasons:

* Performance
* Reflection doesn't show some properties (The ones dynamically added to an object)
* Reflection will happily try to access an undefined property (Declared on the class, but removed from the instance with unset) and throw a notice

It seems the third line applies to uninitialized properties too: By doing it this way it automatically skips uninitialized instance properties. Since we have to use reflection for statics we're coming across uninitialized ones.

This is not very consistent, but it's the quick fix for now. I'd like your feedback into what I should do long-term:

* Hide uninitialized static properties (less info)
* Dig up uninitialized instance properties (less perf)
* Only show uninitialized static properties and ignore uninitialized instance properties (The quick fix I have in now)

Which would be best?

Here's some code to demonstrate what I mean:

```php
class X {
    static string $y;

    public string $z;
}

$x = new X();

d($x);
var_dump($x);
```

**Comment by element-code** [comment]
Long term, i would prefer droping performance in favor of reflecting the reality. I personally think that nothing sucks more than debugging something and gettin wrong debug output.
Maybe do it as a default-on-optin-plugin but i fell like the real state of the instance should get mirrored as close as possible.
-> Dig up uninitialized instance properties (less perf)

**Comment by jnvsor** [comment]
Alrighty. I suppose it's easy enough to skip all but the initialized props in the reflection loop, and we can skip plugins too since there's not much to see if it's uninitialized. I'll use a custom zval.

Unfortunately all the uninitialized properties will be at the top (Or bottom) of the property list. Not in the order they're declared.

If you initialize them afterwards they'll be in declaration order, but since we have to use array casting and reflection to get the full set of possible properties we have to either put the uninitialized or the dynamic properties on their own, and I think the dynamic properties actually containing data are more important.

**Comment by element-code** [comment]
Yeah, declaring them dynamic would be less common so prioitizing dynamic properties would be fine.
I also see no need to replicate the declarion order so thats fine 👍

**Comment by jnvsor** [comment]
@element-code This should be working per 6b3166e873b5cba8f28f4ae82671016d33949340

**Edit:** Sorry to necro, but I'm leaving myself a note for future reference

---

Uninitialized properties in PHP 7.4 and above will be placed "Before" other elements on values.

We could more accurately represent positioning on values by using reflection as the primary source of info and array casting as the backup for dynamically defined properties, but this will error on PHP 7.3 and below as reflection will attempt (And fail) to access predefined but unset properties.

Additionally, since objects are just arrays with some syntactic sugar before 7.4 the ordering in reflection may be completely different from the actual order of the data. If a property defined at the top of the class is unset and reassigned it will be at the end of the object, just like an array.

So until Kint stops supporting 7.3 and below we will keep this behavior, even if the order of uninitialized properties in 7.4 and above is incorrect.
