### ISSUE TITLE
What is this "Elided"?

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#364]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/364220/123413040-f53d4a00-d5ba-11eb-9a09-e12c3a89ff50.png">

I had to google this unused word, and it still left me baffled

    1. omit (a sound or syllable) when speaking.
    "English speakers often elide the vowel completely"
    2. join together; merge.
    "whole periods of time are elided into a few seconds of screen time"

why would my variable dumper cut off display after 20 array keys??? What is going on??

Please consider removing this useless confusing functionality

**Comment by jnvsor** [comment]
Do you really need to see "Auftrag Nr 300001 wurde im aktuellen Archive..." another 105 times?

This skips parsing only in the case of large numeric arrays, something that other dumpers also do for performance reasons. Do you really want to parse everything when you've got an array full of large object hierarchies instead of just strings?

You can always change the values or remove the plugin if you don't want it, but it's been in here for 6 weeks so if you haven't triggered it until the exact use case it's intended for then the thresholds seem more or less correct.

> I had to google this unused word, and it still left me baffled

I was under the impression elision was fairly well known, at least in programming (ie. eliding types that can be statically implied) but I suppose "Omitting" works too - do you think I should change it?

**Comment by raveren** [comment]
I only just switched to dev-master and got this the same day, had to rub my eyes and use the symfony var dumper to find the actual contents of my variable (embarrassing).

There is no indication of **why** was my array trimmed to 20 keys, what were remaining ones, and - sorry - but in general this is a bad feature. Kint was fine for 10 years without this.

Please don't damage usability in such a major way for some theoretical "performance reasons" you can't demonstrate - nor does symfony varDumper have this feature as you claim (I used it to actually see the variable contents).

**Comment by jnvsor** [comment]
> what were remaining ones

I see the remaining keys in your own screenshot...

> nor does symfony varDumper have this feature as you claim

Symfony does, but with a threshold of 2500 items instead of 100... But because symfony vardumper is breadth-first that includes things on child levels.

So if you have 500 items with 10 children each you'll get the full first 250 items and the next 250 will only show the top level, not the children.

![image](https://user-images.githubusercontent.com/5260644/123511142-3d1da900-d66f-11eb-8dd1-c6aaf8bcb51a.png)

And if you have 500 more complex objects with 1000 descendents each you'll get cut off at whatever depth the number runs out.

Needless to say, this isn't much use for a depth-first system, as we'd be going full depth on whatever happens to be the first tree of the dump and then ignoring the rest altogether, and I can't think of a way of going breadth-first and keeping kint's "Killer feature" plugins.

One thing I do notice is that vardumper doesn't trigger this on the top level, only on children. I could parse the remaining items but with the depth limit set so that they are all blacklisted. That would probably be a better solution than what I have now. I'll see if I can do that, but I think I probably made it this way for a reason.

**Comment by jnvsor** [comment]
@raveren I changed it in 496b964f0372ccb6de865119129340acd0d35e31 to act like depth limit - it'll still show each individual item, just not what's below it. Can you try that out and give feedback? If you haven't got any other suggestions I'll put this change on master
