### ISSUE TITLE
Keyboard navigation conflicts with browser 'Find as you type' feature

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#366]
It was a conscious choice to assign a keyboard listener implicitly - instead of **adding** a listener. 

https://github.com/kint-php/kint/blob/ea4320915e53e7003a73f3675cb84e97ea919a6c/resources/js/rich.js#L350

Doing things this way keyboard navigation was not broken with 'Find as you type'.

This is incidently the way everyone does keyboard navigation now - turn on Find as You Type option in Firefox and type <kbd>ga</kbd> in Gmail, or <kbd>t</kbd> in https://github.com/kint-php/kint

Now try navigating Kint with FAYT on - it's frustrating.

This is how it's implemented now:
https://github.com/kint-php/kint/blob/9a7dbea04db5947fc3461736371528af5ca541e2/resources/js/rich.js#L674-L675

Was this a conscious choice, or was this just an accidental regression?

**Comment by jnvsor** [comment]
I was under the impression you should avoid direct assignment precisely because it can't have more than one handler. I had some systems using direct assignment which would break kint keyboard control altogether. (Or the underlying system)

I set the listener to `useCapture` mode for priority and I'm not seeing any issues with fayt when I test. Unless you already opened the fayt search box the handler gets priority when I test it in firefox. Are you seeing different behavior?

Chrome doesn't appear to support fayt out of the box, and I can't find any `window.onkeydown` on github in the inspector (But plenty of keydown event listeners)

**Comment by raveren** [comment]
So this is what happens with `Search for text when you start typing` firefox option on:

https://www.screencast.com/t/660IMQJ81

It's consistent, this is what always happens, is it different on your machine?? The way I used kint for all these years was  by this beautiful, flowing way to see contents of a dump by <kbd>d</kbd>-><kbd>space</kbd>.

**Comment by jnvsor** [comment]
No on my machine it goes straight into kint, it only pops up the search thing if I start with a different key. I'm on FF 88.0.1 - what are you on?

**Comment by raveren** [comment]
there is no longer an About Firefox menu item anywhere lol, but when I click on firefox support in my settings page I get taken to https://support.mozilla.org/1/firefox/89.0.2/Darwin/en-US/preferences

basically just the latest version... ok, lets leave this open and see how this evolves..?

**Comment by jnvsor** [comment]
Alright then, I'd appreciate it if anyone else who comes across the issue could try to reproduce this
