### ISSUE TITLE
JS search not working

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#367]
First time I needed to use it and it's broken unfortunately :(

<img width="861" alt="image" src="https://user-images.githubusercontent.com/364220/127839036-e0ce6d78-227f-4aac-97e3-76ab6e400d90.png">

**Comment by jnvsor** [comment]
Right now search only searches keys, not values. I know it's not ideal but I couldn't get the alternative to perform well in large dumps.

The main issue was that I didn't want it to be basically impossible to search for "string" or "integer" without matching every single variable, so you'd have to search all elements one at a time throughout the tree.

Got any ideas how to solve that?

**Comment by raveren** [comment]
Well, how did the symfony vardumper implement this? Interestingly, their
custom search only comes up in Chrome..

I will take a look what's possible as well, thanks for the reply!

**Comment by jnvsor** [comment]
> Well, how did the symfony vardumper implement this?

I'm pretty sure they can get away with just searching the text content of the parent node because they don't have the data types listed explicitly, but I'm fuzzy on the details

**Comment by jnvsor** [comment]
I've made a new implementation of this. It gets 1501 hits in 400ms searching a clean laravel application for "int"

I went the textContent route for performance purposes and some others.

Plus: We don't have to search children when we know the textContent of the parent has no hits, so performance is improved, and we get a much wider search that handles contents of all the plugins too.

Minus: It's still pretty performance heavy, it's pretty verbose in terms of what it matches ("int" will match a method with "into" in it's docblock deep inside a hierarchy), and we have to clone the dom and remove all access paths _repeatedly_ or else you can't search for the varname you just dumped for example.

@raveren I want to get a feature freeze and beta for 4.x out before 8.1 releases on the 25th - The only reasons I can't release are because github actions' mysql on PHP 8.1 is broken and psalm still has quite a few bugs. Planning on just making psalm a permanent failable test if it doesn't get fixed soon.

Can you try out the search in 6f28460362e2a5e7178041ad9d476ade823b899b and tell me what you think?

**Comment by jnvsor** [comment]
Gonna close this in the meantime, leave a comment if you have any suggestions
