### ISSUE TITLE
Error when including kint.phar in php 8.1

### ISSUE THREAD

**Issue by ipsod** [kint-php/kint#371]
`Kint::trace();`

` Fatal error: Uncaught Error: Undefined constant "Kint\KINT_PHP56" in /var/www/html/php/vendor/kint-php/kint/src/CallFinder.php:144 Stack trace: #0 phar:///var/www/html/php/kint.phar/src/Kint.php(677): Kint\CallFinder::getFunctionCalls() #1 phar:///var/www/html/php/kint.phar/src/Kint.php(459): Kint\Kint::getSingleCall() #2 phar:///var/www/html/php/kint.phar/src/Kint.php(492): Kint\Kint::getCallInfo() #3 /var/www/html/php/world.php(112): Kint\Kint::trace() #4 [internal function]: shutdown_handler() #5 {main} thrown in /var/www/html/php/vendor/kint-php/kint/src/CallFinder.php on line 144`

This is from the kint.phar found at https://github.com/kint-php/kint/raw/master/build/kint.phar just now.

**Comment by jnvsor** [comment]
@ipsod Sorry I'm so late, my mail client died and I didn't realize it.

Your problem seems to be that you have included kint twice. Once at `/var/www/html/php/kint.phar` and once at `/var/www/html/php/vendor/kint-php/kint/`

Normally that wouldn't be a problem, but these are also different versions, with the composer version being 3.x I'd guess (The phar is 4.0-beta1 and doesn't support 5.5 and below any more)

I'm guessing while the phar's init has been loaded the composer autoloader is taking precedence and loading the older code.

Can you confirm that only using one fixes it?

**Comment by ipsod** [comment]
Ah, I see, thank you.  Yes, it seems fixed.
