### ISSUE TITLE
Kint with Content Securiy Policy

### ISSUE THREAD

**Issue by kenjis** [kint-php/kint#376]
When we use [Content Securiy Policy (CSP)](https://content-security-policy.com/), the output of Kint would be like the following:
<img width="811" alt="screenshott 2021-12-23 20 12 23" src="https://user-images.githubusercontent.com/87955/147232503-17cf3860-0aa5-4cdb-b766-f7cefc6b70b2.png">

This is because CSP prevents the `<script>` and `<style>` tags working.

I would like to want the functionality to add `nonce`  like `nonce="Eskdikejidojdk978Ad8jf"` into the tags.

**Comment by jnvsor** [comment]
Hi Kenjis,

The way I implemented this in a similar situation was to subclass the `RichRenderer` and override `preRender` to add a nonce. Then you set `Kint::$renderers[Kint::MODE_RICH]` to the class name of your subclass and it'll use that instead.

Another option would be to empty the `RichRenderer::$pre_render_sources` and add a `raw` source closure to create the tags yourself, but neither are exactly oneliners.

Since CSP is becoming more prevalent I should probably add an option to the `RichRenderer` to set it directly

**Comment by jnvsor** [comment]
@kenjis 71a80e092df1e186bd57b90f4da8fca263409fcc should do the trick - I'll push it to master tomorrow unless you find a problem with it before then

**Comment by jnvsor** [comment]
Pushed. You can set `RichRenderer::$js_nonce` and `RichRenderer::$css_nonce` in master now

**Comment by kenjis** [comment]
Thanks!
It saw it yesterday and seems no problem, but I would like to confirm it.

And when do you plan to release the next one?

**Comment by jnvsor** [comment]
@kenjis I'll just tag it now, it's just a minor anyway

**Comment by setochris** [comment]
Hi, sorry to ask here, but I'm having trouble using this new feature.  I've downloaded the latest version, and am using it like this : 
 Kint\Renderer\RichRenderer::$js_nonce = $my_nonce;

But I get this error : 
 Uncaught Error: Access to undeclared static property Kint\Renderer\RichRenderer::$js_nonce

I've added other Kint settings in a similar way without any problems.  Can someone let me know what I'm doing wrong, or perhaps it's not in the latest download yet?  Thanks for your help.

**Comment by kenjis** [comment]
The following code generates `<script class="kint-rich-script" nonce="abcdef">...`.
```php
<?php
require __DIR__ . '/vendor/autoload.php';
Kint\Renderer\RichRenderer::$js_nonce = 'abcdef';
d('test');
```

It seems that you are not using 4.1.

**Comment by setochris** [comment]
I've just downloaded the latest .phar file from "Download Master Phar" on the main page.  I'm not using autoload, just including the kint.phar file in my script.   I think you right that I don't have the latest 4.1, but I'm not sure where to get it.  I tried downloading the latest .phar in the github build folder, but it's not working either.  

Update, so I found the link to the version 4.1 zip, but it does not include a prebuilt .phar file.  Any chance on getting that added to the zip?  Thanks

**Comment by jnvsor** [comment]
@setochris I just downloaded the master phar and I can confirm the `$js_nonce` property does exist. You can also download the phar from the repo directly: https://github.com/kint-php/kint/tree/master/build

It's potentially a caching issue in your browser... Not sure I can fix that in the site since the file itself is being served by github

**Edit:** In theory that could be fixed by appending a timestamp to the request... So I'll write some JS to do that... It just won't work if you have JS disabled, but that's not a huge subset of users

**Edit 2:** @setochris Done - if you refresh the site page the link should be cache-busted with a query param so your browser downloads the latest. Let me know how it goes

**Comment by setochris** [comment]
Thanks so much for your help.  Strange I did try clearing cache, and downloading it several times but it still never worked.  Seems to be working fine now though, really appreciate all the help.
