### ISSUE TITLE
Specify CLI stream, and invoke CLI output from web server

### ISSUE THREAD

**Issue by DRSDavidSoft** [kint-php/kint#380]
Would it be possible to configure Kint to output to `STDERR`, or `STDOUT` even if the `PHP_SAPI` isn't `cli`?

**Why this would be useful:** 
- If running the following command: `php test.php > output.txt`, it would be possible to redirect Kint output to `STDERR`, in order to display debugging info.
  (I already redirect PHP's fatal errors and uncaught exceptions to `STDERR`, so this would fit right in)
  Additionally, the output does not need to be named `windows_stream` -- rather `cli_output_stream`
- It is possible to still output to the console, when running `php -S <ip>:<port>` server.  I haven't used Kint this way, but sometimes in my script I directly write to the console from my web PHP scripts, this allows quickly identifying errors and warnings, particularly when the PHP script is for example returning a JSON response, so neither the rich HTML renderer nor the plain text could be used in the JSON response, as it would invalidate the output.
   In these scenarios, I've mainly printed to `STDERR` information (also using simple color  escape codes) 

So, it'd be useful if we could invoke Kint's CLI output from the CGI (web) script, and also have the ability to specify to which stream it should write the response.

**Comment by jnvsor** [comment]
Well currently kint either returns or echoes its output (So it should be going to STDOUT in CLI too)

If you want to customize it a bit you could replace (or copy) `d()`, have `Kint` return its output, and then write to stderr instead of echoing.

I'll look into how this works in apache, but I suspect that it'll result in (for example) the full HTML output being dumped to your log files or console.

**Comment by DRSDavidSoft** [comment]
Ideally, it could be possible to return the color+utf-8 formatted text output, even from the web-server.

Here's what I'm testing:  
![cgi](https://user-images.githubusercontent.com/4673812/147875369-f73a74e9-a457-4786-af8d-1213de9908df.png)

Result in the cli:  
![cli](https://user-images.githubusercontent.com/4673812/147875378-6dfed619-da05-4132-8bb4-f21ad3cbdb4b.png)

I'm testing this with the built-in web server, not sure if the same idea would work on apache and/or other cgi servers (e.g. IIS).

For now, I'll close this issue as `init_helpers.php` can be customized for these needs.

Just one question, how to specify for Kint to return its output instead of `echo`ing it?

**Comment by jnvsor** [comment]
> how to specify for Kint to return its output

There are a few ways, such as calling `@Kint::dump` or setting `Kint::$return` - the docs are all on the site: https://kint-php.github.io/kint/ (If you have any suggestions on clarity there I'll take them, I feel like they could use an update)

Yeah now that I think about it, this is probably impossible to do correctly automatically.

In your example you want CLI output because it's using the development server, but in apache stderr would go to log files where you'd want text rendering instead (The CLI output would involve a bunch of control codes for color being dumped into log files which is a bad idea)

PHP has (in principle) no knowledge of where stderr goes so you'd have to default to `TextRenderer` for it. I think it's better to leave that to the users, though I could see myself making a helper to do this in a separate package

> `init_helpers.php` can be customized for these needs

There are a couple of ways to override them without having to change the code itself. Again the docs have more info
