### ISSUE TITLE
How to customise the title access_path

### ISSUE THREAD

**Issue by jonnybradley** [kint-php/kint#387]
Hi

This isn't really an issue but a question, hope that's ok - i've been banging my head on this for too long now.

I want to use Kint with the Smarty template system and want to make the title "access path" more user friendly (it currently appears as `$_smarty_tpl->tpl_vars[...]->value` where the `...` bit is actually replacing the important var name), is there a way to customise that? I tried writing a plugin but that seems to only be involved after the title bar has been rendered... is there a way of doing that? Ideally i'd like to supply a custom function with the top level base `Value` object as the parameter.

Thanks in advance, and thanks for such a fabulous utility, don't know how i managed without it!

**Comment by jnvsor** [comment]
Hi @jonnybradley there are a few different ways of doing this.

If you want the "Quick 'n dirty" way of doing it you can create your own function for smarty that calls `Kint::dumpAll` (Which is called internally by `Kint::dump`) with custom access paths, but this will only work for things you dump directly with it.

Otherwise you'll want a [parser plugin](https://kint-php.github.io/kint/writing-plugins/#example) that targets top level `Smarty_Variable` objects on `Parser::TRIGGER_BEGIN` and just parses the `$var->tpl_vars[...]->values` directly. This is the "proper" way of doing it but a bit more involved. The example should get you most of the way there

**Comment by jnvsor** [comment]
Going to close this, leave a message if you need more help

**Comment by jonnybradley** [comment]
Brilliant, thanks @jnvsor - i was pretty close i think, once i had the `Parser::TRIGGER_BEGIN ` clue i got just what i needed... Pushed to Tiki now in https://gitlab.com/tikiwiki/tiki/-/commit/86d2db1f 🤓

Thanks again!

**Comment by jnvsor** [comment]
@jonnybradley Yep, that looks about right

You might want to make sure that `$o->depth` is 0 so that this only applies to toplevel variables, and maybe make the regex more specific, otherwise it will blow away any access path that looks similar (But making it more specific makes it more likely to fail. Up to you)

Untested pseudocode (You don't need the extra trigger check):

```php
public function parse(&$var, Value &$o, $trigger)
{
    if ($o->depth == 0 && preg_match('/\\$_smarty_tpl->tpl_vars[\'(.*?)\']->value/', $o->access_path, $match)) {
        $o->access_path = '$'.$match[1];
    }
}
```

**Comment by jonnybradley** [comment]
Thanks, i didn't spot the depth property, but in my local testing it only seemed to be triggered once at the top level (but will probably add that), and yes, i considered making the regex more specific but thought i'd leave it a bit loose to catch other types of internal smarty values in other contexts - will fine tune this over time no doubt, many thanks again for your help and input!
