### ISSUE TITLE
How to use a plugin?

### ISSUE THREAD

**Issue by viharm** [kint-php/kint#395]
I've returned to PHP after a few years and, being a true _Kint_ fan, it was the first thing I installed in my project (which is obviously too tiny for _Kint_  😆). I am pleasantly surprised by the way _Kint_ has grown over the years, especially the helpers and plugins - Wow!!!

I noticed that there is a JSON parser plugin, which I want to use as I debug my script.

Here's a weird question, which I couldn't answer after scouring the docs... "How are plugins used?" The docs show how to use the helper functions, but not the plugins. For parsers, do they automatically detect?

I feel it will help newcomers if there was an example of the usage of a parser (except for the one-line mention of the _Blacklist_ plugin in the README.

Again, _Kint_ is awesome! My sincere thanks to the developers :-)

**Comment by jnvsor** [comment]
Most of the kint-specific 1.x features were moved to plugins in 2.x, and the JSON plugin is actually on by default: if kint encounters a (valid) json string it'll parse it for you (And give you the full expression needed to access specific subitems etc.)

You're right that I apparently forgot to mention how to enable them in the docs, I'll fix that now (Short version: Add the plugin classname or instance to `Kint::$plugins`)

**Comment by viharm** [comment]
> Most of the kint-specific 1.x features were moved to plugins in 2.x, and the JSON plugin is actually on by default: if kint encounters a (valid) json string it'll parse it for you (And give you the full expression needed to access specific subitems etc.)
> 
> You're right that I apparently forgot to mention how to enable them in the docs, I'll fix that now (Short version: Add the plugin classname or instance to `Kint::$plugins`)

OK, this is just awesome! Firstly thanks for the lightning fast response. Secondly, I'm blown away by the fact that it can auto-detect. However I'm a bit lost, that it isn't doing that. I'm on pure CLI. Do I need to do anything different?

**Comment by jnvsor** [comment]
@viharm Yeah most plugins are disabled on CLI - most of it results in multiple different representations of data, for instance you may want to see the JSON unfolded, or you may want to just see the string. You may want to see the exception properties, or you may want to see the stack trace. You might want to see the contents of a `SimpleXMLElement` or you might want to see the attributes.

Lots of features like that fit into tabs under a single value when you're in the rich HTML view, but if you were to just list them all one after the other in plain text it becomes an impenetrable mess. Take a look at the live demo on the site handles json/colors/tables and then imagine all those tabs (With often duplicate information) being dumped at once and you'll see why plaintext only renders the "Main" value

If you look at [TextRenderer](https://github.com/kint-php/kint/blob/0518ee9e1b5b3c7bbf3c9ad837a6591e39dbfab0/src/Renderer/TextRenderer.php#L38) you can see the only interesting plugins enabled are the `microtime()` `debug_backtrace()` and stream resource ones

**Edit:** If you still want to see the JSON contents instead of the string, Kint's been made a lot more extensible over the years. You can whitelist the JSON plugin and write a plugin that swaps in the hierarchy as the value instead of the string (But most people don't need custom plugins, since they tend to just use it in web pages and that's _good enough_)

**Comment by viharm** [comment]
@jnvsor , thanks very much for your patient explanation. I understand (& agree with) the approach used. And yes, _Kint_ has indeed come a long way. Unfortunately I am unable to write a plugin to augment the heirarchical JSON output due to time constraints, so will resort to decoding the JSON string, and then dumping it with _Kint_ (I may write something later and suggest a change). Thanks again to the entire team for the hard work.

**Comment by jnvsor** [comment]
```php
class JsonValuePlugin extends Kint\Parser\Plugin
{
    public function getTypes(): array
    {
        return ['string'];
    }

    public function getTriggers(): int
    {
        return Kint\Parser\Parser::TRIGGER_SUCCESS;
    }

    public function parse(&$var, Kint\Zval\Value &$o, int $trigger)
    {
        if ($r = $o->getRepresentation('json')) {
            $o->value = $r;
        }
    }
}
Kint::$plugins[] = new JsonValuePlugin();
```

That should do the trick (Not tested at all though)

You'd have to add that after the `JsonPlugin` and whitelist them both in `TextRenderer`
