### ISSUE TITLE
RTL rendering

### ISSUE THREAD

**Issue by jnvsor** [kint-php/kint#427]
From @DRSDavidSoft in #422

> Fix RTL issue: Kint isn't supposed to render in the RTL (Right-to-left) mode. If the direction of page (or the parent element) is set to RTL, then Kint wouldn't display properly. I believe it would be better to force direction: ltr into the Kint themes.

**Comment by jnvsor** [comment]
@DRSDavidSoft Does d6350e15ade21b3f49e349ed5fbfd51e743fecca fix the RTL issue? While the dump now looks fine on an RTL page I'm not sure how it'll affect RTL text inside dumps

**Comment by DRSDavidSoft** [comment]
This sure does fix the Kint rendering. You are right about RTL text inside the dumps, but I believe this is expected behavior among devs who work with RTL content; If the content needs alternative direction, you need to apply it outside the dumping utility.

Alternative approach would be to use JS to apply the parent element's direction to it, or provide some manual override function... These don't really make sense for a dumper utility when there is a custom theming function available; I believe it's up to the user to provide their own CSS to deal with RTL text inside Kint. To me, the correct rendering of the Kint's rich renderer is far more important.

I suggest merging this PR as is, and maybe adding a note regarding RTL use in the docs. Please tell me which would suit Kint best, I'll help with that solution.

Also thanks for the quick addition of this to the scss! 😄 👍🏻 

Lack of this was truly a pain point when trying to debug RTL apps, I always needed to apply this manually to the stylesheet of the application.

**Comment by jnvsor** [comment]
> You are right about RTL text inside the dumps, but I believe this is expected behavior among devs who work with RTL content

Alright, then that's what we'll use, thanks for feedback
