### ISSUE TITLE
Problem on handling json response via CURL Request

### ISSUE THREAD

**Issue by cevarief** [kint-php/kint#98]
When doing CURL request, the json string response can not be decoded since Kint will add js code to the response string.

`$response = '{"success":true}<script>(function(){if("undefined"!==typeof jQuery) ....'`
`json_decode($response)` will return NULL.

I guess there should be global config/option for condition so it won't run ajaxHandler on shutdown.

`if ( Kint::$_detected !== 'ajax' && Kint::$_detected !== 'cli' ) {
    //register_shutdown_function( 'Kint::_ajaxHandler' ); <-- i comment this line atm
}`

**Comment by raveren** [comment]
Yeah, I've disabled this by default, this behaviour is caused by non-concistencies in the users system, but it's a bad thing when it happens.

Basically, there is no fool-proof way to detect whether the request is ajax, or not. The most common JS libraries like mootools and jQuery ad a `x-requested-with` header which I check. I also check the generated response headers to contain the default `Content-type: xhtml`, so if you'd be doing everything "properly", there wouldn't be a problem, but this is a utopia in real world scenarios, and most users will have problems.

Thank you for the issue, I'll push my local changes in the few comming days.
